// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nifty-dashboard/Editorial.tsx": () => import("../components/mockups/nifty-dashboard/Editorial.tsx"),
  "./components/mockups/nifty-dashboard/Spotlight.tsx": () => import("../components/mockups/nifty-dashboard/Spotlight.tsx"),
  "./components/mockups/nifty-dashboard/Terminal.tsx": () => import("../components/mockups/nifty-dashboard/Terminal.tsx")
};
